### ISSUE TITLE
1.12 compatibility

### ISSUE THREAD

**Issue by PugaBear** [dvargas135/eZProtector#38]
Will need an update for 1.12 (see spigot homepage for pre-release info)

**Comment by GiansCode** [comment]
Spigot 1.12-Pre is for finding bugs and not meant for production. Once a stable build drops, I will add this.

**Comment by PugaBear** [comment]
I personally think its an opportunity for plugin developers to get ahead of the game.. but you do you

**Comment by GiansCode** [comment]
The issue is, 1.12 removes a lot of previously deprecated methods. As the API is still in a prerelease stage, I don't want to do anything now in the event something changes.

Not everyone will want to use 1.12 when it comes out, so, I need to implement work arounds to ensure it works on previous versions (at least until 1.8). The update is a bug fix update, and feature introduction, too. I don't want guys to miss out on it.

**Comment by PsychoLynx** [comment]
Hi!

Another person here looking forward to the update :) Thank you for your great work in making our server safe <3

**Comment by Kizarr** [comment]
The full release is out. May you please update whenever you get the chance. This is like one of my favorite plugins of all time.
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12.246398/

**Comment by GiansCode** [comment]
1.12 update will be coming soon! It's a major update and will drop support for versions below 1.9

**Comment by caxerx** [comment]
There are some problem, this plugin is already depend on ProtocolLib. So why don't use ProtocolLib to handle the packet part instead of NMS?
